version: 0.0
os: linux
files:
  - source: /dist
    destination: /data/mobi-webview-pages/dist
  - source: /ansible
    destination: /data/mobi-webview-pages/ansible
  - source: /appspec.yml
    destination: /data/mobi-webview-pages/
permissions:
  - object: /data
    pattern: "mobi-webview-pages"
    owner: nginx
    group: root
    mode: 554
    type:
      - directory
  - object: /data/mobi-webview-pages
    pattern: "dist"
    owner: nginx
    group: root
    mode: 554
    type:
      - directory
  - object: /data/mobi-webview-pages/dist
    pattern: "**"
    owner: nginx
    group: root
    mode: 664
    type:
      - file
  - object: /data/mobi-webview-pages/ansible/scripts
    pattern: "**"
    owner: nginx
    group: root
    mode: 755
    type:
      - file
hooks:
   AfterInstall:
       - location: ansible/scripts/after_install.sh 
         timeout: 3600
   
